In [62]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


df = pd.read_csv("/Users/rathsusan/Documents/Applied-Machine-Learning-Project/Data/Raw/online_shoppers_intention 2.csv")
df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,Month,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,Feb,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,Feb,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,Feb,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,Feb,3,3,1,4,Returning_Visitor,True,False

In [63]:
df.isnull().sum

<bound method DataFrame.sum of        Administrative  Administrative_Duration  Informational  \
0               False                    False          False
1               False                    False          False
2               False                    False          False
3               False                    False          False
4               False                    False          False
...               ...                      ...            ...
12325           False                    False          False
12326           False                    False          False
12327           False                    False          False
12328           False                    False          False
12329           False                    False          False

       Informational_Duration  ProductRelated  ProductRelated_Duration  \
0                       False           False                    False
1                       False           False                    False
2                       False           False                    False
3                       False           False                    False
4                       False           False                    False
...                       ...             ...                      ...
12325                   False           False                    False
12326                   False           False                    False
12327                   False           False                    False
12328                   False           False                    False
12329                   False           False                    False

       BounceRates  ExitRates  PageValues  SpecialDay  Month  \
0            False      False       False       False  False
1            False      False       False       False  False
2            False      False       False       False  False
3            False      False       False       False  False
4            False      False       False       False  False
...            ...        ...         ...         ...    ...
12325        False      False       False       False  False
12326        False      False       False       False  False
12327        False      False       False       False  False
12328        False      False       False       False  False
12329        False      False       False       False  False

       OperatingSystems  Browser  Region  TrafficType  VisitorType  Weekend  \
0                 False    False   False        False        False    False
1                 False    False   False        False        False    False
2                 False    False   False        False        False    False
3                 False    False   False        False        False    False
4                 False    False   False        False        False    False
...                 ...      ...     ...          ...          ...      ...
12325             False    False   False        False        False    False
12326             False    False   False        False        False    False
12327             False    False   False        False        False    False
12328             False    False   False        False        False    False
12329             False    False   False        False        False    False

       Revenue
0        False
1        False
2        False
3        False
4        False
...        ...
12325    False
12326    False
12327    False
12328    False
12329    False

[12330 rows x 18 columns]>

In [64]:
df.dtypes

Administrative               int64
Administrative_Duration    float64
Informational                int64
Informational_Duration     float64
ProductRelated               int64
ProductRelated_Duration    float64
BounceRates                float64
ExitRates                  float64
PageValues                 float64
SpecialDay                 float64
Month                       object
OperatingSystems             int64
Browser                      int64
Region                       int64
TrafficType                  int64
VisitorType                 object
Weekend                       bool
Revenue                       bool
dtype: object

In [65]:
# Drop Month feature 
df = df.drop(columns=['Month'])

In [66]:
df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,PageValues,SpecialDay,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,0.0,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,0.0,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,0.0,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,0.0,3,3,1,4,Returning_Visitor,True,False

In [67]:
#drop pagevalues to prevent dataleakage
df = df.drop(columns=['PageValues'])
df.head()

,Administrative,Administrative_Duration,Informational,Informational_Duration,ProductRelated,ProductRelated_Duration,BounceRates,ExitRates,SpecialDay,OperatingSystems,Browser,Region,TrafficType,VisitorType,Weekend,Revenue
0,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,1,1,1,1,Returning_Visitor,False,False
1,0,0.0,0,0.0,2,64.000000,0.00,0.10,0.0,2,2,1,2,Returning_Visitor,False,False
2,0,0.0,0,0.0,1,0.000000,0.20,0.20,0.0,4,1,9,3,Returning_Visitor,False,False
3,0,0.0,0,0.0,2,2.666667,0.05,0.14,0.0,3,2,2,4,Returning_Visitor,False,False
4,0,0.0,0,0.0,10,627.500000,0.02,0.05,0.0,3,3,1,4,Returning_Visitor,True,False

In [68]:
categorical_cols = ['OperatingSystems', 'Browser', 'Region', 'TrafficType', 'VisitorType']

# Apply one-hot encoding
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

In [69]:
df.columns

Index(['Administrative', 'Administrative_Duration', 'Informational',
       'Informational_Duration', 'ProductRelated', 'ProductRelated_Duration',
       'BounceRates', 'ExitRates', 'SpecialDay', 'Weekend', 'Revenue',
       'OperatingSystems_2', 'OperatingSystems_3', 'OperatingSystems_4',
       'OperatingSystems_5', 'OperatingSystems_6', 'OperatingSystems_7',
       'OperatingSystems_8', 'Browser_2', 'Browser_3', 'Browser_4',
       'Browser_5', 'Browser_6', 'Browser_7', 'Browser_8', 'Browser_9',
       'Browser_10', 'Browser_11', 'Browser_12', 'Browser_13', 'Region_2',
       'Region_3', 'Region_4', 'Region_5', 'Region_6', 'Region_7', 'Region_8',
       'Region_9', 'TrafficType_2', 'TrafficType_3', 'TrafficType_4',
       'TrafficType_5', 'TrafficType_6', 'TrafficType_7', 'TrafficType_8',
       'TrafficType_9', 'TrafficType_10', 'TrafficType_11', 'TrafficType_12',
       'TrafficType_13', 'TrafficType_14', 'TrafficType_15', 'TrafficType_16',
       'TrafficType_17', 'TrafficType_18', 'TrafficType_19', 'TrafficType_20',
       'VisitorType_Other', 'VisitorType_Returning_Visitor'],
      dtype='object')

In [70]:
df.dtypes

Administrative                     int64
Administrative_Duration          float64
Informational                      int64
Informational_Duration           float64
ProductRelated                     int64
ProductRelated_Duration          float64
BounceRates                      float64
ExitRates                        float64
SpecialDay                       float64
Weekend                             bool
Revenue                             bool
OperatingSystems_2                  bool
OperatingSystems_3                  bool
OperatingSystems_4                  bool
OperatingSystems_5                  bool
OperatingSystems_6                  bool
OperatingSystems_7                  bool
OperatingSystems_8                  bool
Browser_2                           bool
Browser_3                           bool
Browser_4                           bool
Browser_5                           bool
Browser_6                           bool
Browser_7                           bool
Browser_8                           bool
Browser_9                           bool
Browser_10                          bool
Browser_11                          bool
Browser_12                          bool
Browser_13                          bool
Region_2                            bool
Region_3                            bool
Region_4                            bool
Region_5                            bool
Region_6                            bool
Region_7                            bool
Region_8                            bool
Region_9                            bool
TrafficType_2                       bool
TrafficType_3                       bool
TrafficType_4                       bool
TrafficType_5                       bool
TrafficType_6                       bool
TrafficType_7                       bool
TrafficType_8                       bool
TrafficType_9                       bool
TrafficType_10                      bool
TrafficType_11                      bool
TrafficType_12                      bool
TrafficType_13                      bool
TrafficType_14                      bool
TrafficType_15                      bool
TrafficType_16                      bool
TrafficType_17                      bool
TrafficType_18                      bool
TrafficType_19                      bool
TrafficType_20                      bool
VisitorType_Other                   bool
VisitorType_Returning_Visitor       bool
dtype: object